### ISSUE TITLE
Tensor.SameChars test has non-deterministic outcomes

### ISSUE THREAD

**Issue by ajoudaki** [ratschlab/Project2020-seq-tensor-sketching#29]
Outcome of test cases must be deterministic, not dependent on any random device

**Comment by danieldanciu** [comment]
I agree that tests should be deterministic.
Here however, I think the problem is not the test, but the TS
implementation. The test is pointing out that TS is returning an unexpected
result.

**Comment by RagnarGrootKoerkamp** [comment]
Fixed by https://github.com/ratschlab/Project2020-seq-tensor-sketching/commit/56f962ea3e870f7df011ae275369be9f45afe373: the constructor had the wrong variable passed in
