### ISSUE TITLE
more readme and help info

### ISSUE THREAD

**Issue by jianshu93** [ratschlab/Project2020-seq-tensor-sketching#48]
Hello Tensor sketch team,

Many thanks for this wonderful tool. With exact kmer method not perfect for distantly related sequences, spacer-kmer is a smart idea. I can successfully compile the whole thing and have several binaries like seqgen, experiments, tests and sketch. But I am really confused to use the sketch command for my own fasta sequences due to no help info for each positional argument for the sketch binary. I am reading the main cpp of sketch to have a better understanding but fails because of lack of annotation. Can you please help how exactly I can run the sketch command for my own sequences. and Does tensor sketch take into account sequences length? I think it does because the number of sliding windows will be different for different sequences in length.

Many thanks,

Jianshu

**Comment by danieldanciu** [comment]
Hey Jianshu -

Here are the instructions on how to run the tensor sketching binary:

https://github.com/ratschlab/Project2020-seq-tensor-sketching

Hope that helps,
Daniel
